name: Makefile CI

on:
  push:
    branches: [ "winrt" ]
  pull_request:
    branches: [ "winrt" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.6.1
      with:
         python-version: 2.7
    - name: Install xmllint
      run: sudo apt-get install arm-linux-gnueabihf-gcc
    - name: step1
      run: make -C BaseTools
    - name: step2
      run: source edksetup.sh

    - name: step3
      run: export GCC49_ARM_PREFIX=arm-linux-gnueabihf-

    - name: step4
      run:  export GCC49_ARM_PREFIX=arm-linux-gnueabihf-&& export WORKSPACE=/home/runner/work/edk2-winrt/edk2-winrt && export EDK_TOOLS_PATH=/home/runner/work/edk2-winrt/edk2-winrt/BaseTools && export CONF_PATH=/home/runner/work/edk2-winrt/edk2-winrt/Conf && ./BaseTools/BinWrappers/PosixLike/build -a ARM -t GCC49 -b RELEASE -p ArmVirtPkg/ArmVirtQemuWinRt.dsc
